name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Keystore
        run: |
          [ "${{ secrets.RELEASE_STORE_BASE64}}" == "" ] || echo "${{ secrets.RELEASE_STORE_BASE64}}" | base64 -d > keystore.jks
      - name: Build with Gradle
        env:
          CI_VERSION: ${{ github.ref }}
          CI_BUILD_NUMBER: ${{ github.run_number }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          export RELEASE_STORE_FILE="$(readlink -f keystore.jks)"
          if [ -e keystore.jks ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi
      - uses: actions/upload-artifact@v3
        with:
          path: 'app/build/outputs/apk/release/*.apk'
