name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Keystore
        run: |
          [ "${{ secrets.RELEASE_STORE_BASE64}}" == "" ] || echo "${{ secrets.RELEASE_STORE_BASE64}}" | base64 -d > keystore.jks
      - name: Build with Gradle
        env:
          CI_VERSION: ${{ github.ref }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          export GIT_COMMIT_COUNT="$(git rev-list --all --count)"
          export RELEASE_STORE_FILE="$(readlink -f keystore.jks)"
          if [ -e keystore.jks ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi
          mv app/build/outputs/apk/*/*.apk .
      - uses: actions/upload-artifact@v3
        with:
          path: '*.apk'
