name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Keystore
        run: |
          [ "${{ secrets.RELEASE_STORE_BASE64}}" != "" ] && echo "${{ secrets.RELEASE_STORE_BASE64}}" | base64 -d > keystore.jks
      - name: Build with Gradle
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          export RELEASE_STORE_FILE="$(readlink -f keystore.jks)"
          if [ -e keystore.jks ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assemble
          fi
      - uses: actions/upload-artifact@v2
        with:
          path: 'app/build/outputs/apk/release/*.apk'
