name: release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Keystore
        run: echo "${{ secrets.RELEASE_STORE_BASE64}}" | base64 -d > keystore.jks
      - name: Build with Gradle
        env:
          CI_VERSION: ${{ github.ref }}
          CI_BUILD_NUMBER: ${{ github.run_id }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          export RELEASE_STORE_FILE="$(readlink -f keystore.jks)"
          ./gradlew assembleRelease
      - uses: actions/upload-artifact@v2
        with:
          path: 'app/build/outputs/apk/release/*.apk'
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'app/build/outputs/apk/release/*.apk'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
